[package]
name = "anal"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5.4"
walkdir = "2.3.2"
rayon = "1.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-cuda = "0.1"
#rustacuda = "0.1"
#rustacuda_core = "0.1"
#rustacuda_derive = "0.1"
